universe = vanilla
sample = PbPb23
fom = punzi
sample_output_dir = xgb_outputs/ntmix_PbPb/pbpb23_punzi
trials = 250
n_rounds = 1000
early_stopping = 100
max_signal = 165000
max_background = 500000
summary_subdir = optuna_summaries
njobs = 250

initialdir = /eos/user/h/hmarques/Analysis_CODES/selectionER/ML_xgboost
executable = run_optuna_batch.sh
arguments = XGB_optuna.py --sample $(sample) --fom $(fom) --trials $(trials) --n-rounds $(n_rounds) --early-stopping $(early_stopping) --max-signal $(max_signal) --max-background $(max_background) --summary-subdir $(summary_subdir) --scan-tag $(ClusterId) --seed $(ProcId)

transfer_input_files = XGB_optuna.py, XGB_train.py, ../ML_common/ml_fom.py, ../ML_common/ml_samples.py, ../ML_common/ml_decorrelation.py
transfer_output_files = $(sample_output_dir)/$(summary_subdir)/optuna_summary_$(sample)_$(fom)_$(ClusterId)_seed$(ProcId).json

output = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId)_$(ProcId).out
error = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId)_$(ProcId).err
log = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId).log

getenv = False
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 4
request_memory = 8 GB
request_disk = 2 GB
requirements = (OpSysAndVer == "AlmaLinux9")
+JobFlavour = "tomorrow"

queue $(njobs)
