universe = vanilla
sample = PbPb23
fom = punzi
sample_output_dir = nn_outputs/ntmix_PbPb/pbpb23_punzi
trials = 100
max_epochs = 150
early_stopping = 15
timeout_hours = 20
max_signal = 165000
max_background = 500000
summary_subdir = optuna_summaries
njobs = 200
summary_name = optuna_summary_$(sample)_$(fom)_$(ClusterId)_seed$(ProcId).json

initialdir = /eos/user/h/hmarques/Analysis_CODES/selectionER/ML_pytorch
executable = run_nn_batch.sh
arguments = NN_optuna.py --sample $(sample) --fom $(fom) --trials $(trials) --max-epochs $(max_epochs) --early-stopping $(early_stopping) --timeout-hours $(timeout_hours) --max-signal $(max_signal) --max-background $(max_background) --summary-subdir $(summary_subdir) --scan-tag $(ClusterId) --seed $(ProcId)

transfer_input_files = NN_optuna.py, NN_train.py, ../ML_common/ml_fom.py, ../ML_common/ml_samples.py, ../ML_common/ml_decorrelation.py
transfer_output_files = $(sample_output_dir)/$(summary_subdir)/$(summary_name)

output = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId)_$(ProcId).out
error = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId)_$(ProcId).err
log = condor_logs/optuna_$(sample)_$(fom)_$(ClusterId).log

getenv = False
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 4
request_memory = 8 GB
request_disk = 2 GB
requirements = (OpSysAndVer == "AlmaLinux9")
+JobFlavour = "tomorrow"

queue $(njobs)
